name: Kash by Suchi
tagline: Elegant sustainable ethnic jewellery, made to last longer than the trend.
about: Kash by Suchi is simply ethnic for people who love the earth
email: devarajan.sridharan@gmail.com
instagram: "@maisonlumiere"
