name: Kash by Suchi
tagline: Fine Sustainable costume jewellery, made to last longer than the trend.
about: Kash by Suchi designs Sustainable Ethnic jewellery for people who want
  the look of fine jewellery without the formality. Every piece is hand-finished
  in single unique pieces and made with terracotta, finely handcrafted and
  designed. It is elegant for workwear and modern outfits and stylish and
  grandeur for traditional outfits
email: devarajan.sridharan@gmail.com
instagram: "@maisonlumiere"
